// <auto-generated />
using System;
using JobTrackrAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTrackrAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008164252_addEmployerSponsorshipStat")]
    partial class addEmployerSponsorshipStat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTrackrAPI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobTrackrAPI.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobTrackrAPI.Models.EmployerSponsorshipStat", b =>
                {
                    b.Property<string>("EmployerKey")
                        .HasColumnType("text")
                        .HasColumnName("employer_key");

                    b.Property<decimal>("CertificationRate")
                        .HasColumnType("numeric")
                        .HasColumnName("certification_rate");

                    b.Property<int>("CertifiedFilings")
                        .HasColumnType("integer")
                        .HasColumnName("certified_filings");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employer_name");

                    b.Property<DateTime?>("MostRecentDecision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("most_recent_decision");

                    b.Property<string>("TopJobTitle")
                        .HasColumnType("text")
                        .HasColumnName("top_job_title");

                    b.Property<int>("TotalFilings")
                        .HasColumnType("integer")
                        .HasColumnName("total_filings");

                    b.Property<decimal?>("TypicalWageFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("typical_wage_from");

                    b.Property<decimal?>("TypicalWageTo")
                        .HasColumnType("numeric")
                        .HasColumnName("typical_wage_to");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EmployerKey");

                    b.ToTable("employer_sponsorship_stats");
                });

            modelBuilder.Entity("JobTrackrAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
